import { Category, Product, ShopSettings, HeroBanner, Coupon } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Daily Essentials', name_urdu: 'روزمرہ سبزیاں', slug: 'daily-essentials', icon: '🥔', sort_order: 1 },
  { id: 'cat-2', name: 'Fresh Greens', name_urdu: 'ہری سبزیاں', slug: 'fresh-greens', icon: '🥬', sort_order: 2 },
  { id: 'cat-3', name: 'Salad & Herbs', name_urdu: 'سلاد اور مصالحہ جات', slug: 'salad-herbs', icon: '🥒', sort_order: 3 },
  { id: 'cat-4', name: 'Seasonal Specials', name_urdu: 'موسمی سبزیاں', slug: 'seasonal-specials', icon: '🌽', sort_order: 4 },
  { id: 'cat-5', name: 'Family Bundles', name_urdu: 'فیملی کریٹس اور بنڈلز', slug: 'family-bundles', icon: '🧺', sort_order: 5 }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    category_id: 'cat-1',
    name: 'Red Potatoes (Aloo)',
    name_urdu: 'لال آلو',
    slug: 'red-potatoes-aloo',
    description: 'Firm, fresh farm-harvested red potatoes perfect for daily cooking, handi, and fries.',
    price: 90,
    unit: 'kg',
    weight_options: ['0.5', '1', '2', '5'],
    stock: 150,
    is_active: true,
    is_featured: true,
    badge: 'Fresh Daily',
    thumbnail_url: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'prod-2',
    category_id: 'cat-1',
    name: 'Sindhi Onions (Piyaz)',
    name_urdu: 'سندھی پیاز',
    slug: 'sindhi-onions-piyaz',
    description: 'Dry, premium quality Sindh onions with strong flavor and rich layers.',
    price: 130,
    unit: 'kg',
    weight_options: ['0.5', '1', '2', '5'],
    stock: 120,
    is_active: true,
    is_featured: true,
    badge: 'Best Seller',
    thumbnail_url: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'prod-3',
    category_id: 'cat-1',
    name: 'Fresh Farm Tomatoes (Tamatar)',
    name_urdu: 'تازہ ٹماٹر',
    slug: 'fresh-farm-tomatoes-tamatar',
    description: 'Plump, juicy, naturally ripened red tomatoes. Ideal for salan, gravy, and fresh salads.',
    price: 140,
    unit: 'kg',
    weight_options: ['0.5', '1', '2', '5'],
    stock: 95,
    is_active: true,
    is_featured: true,
    badge: 'Top Pick',
    thumbnail_url: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'prod-4',
    category_id: 'cat-1',
    name: 'Desi Garlic (Lehsan)',
    name_urdu: 'دیسی لہسن',
    slug: 'desi-garlic-lehsan',
    description: 'Strong aroma desi garlic cloves with intense flavor and natural medicinal qualities.',
    price: 380,
    unit: 'kg',
    weight_options: ['0.25', '0.5', '1'],
    stock: 60,
    is_active: true,
    is_featured: false,
    badge: 'Aroma Rich',
    thumbnail_url: 'https://images.unsplash.com/photo-1615477032219-bc1881ba87ab?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'prod-5',
    category_id: 'cat-1',
    name: 'Fresh Ginger (Adrak)',
    name_urdu: 'تازہ ادرک',
    slug: 'fresh-ginger-adrak',
    description: 'Clean, spicy ginger roots without excess fiber. Essential for Pakistani curries and chai.',
    price: 480,
    unit: 'kg',
    weight_options: ['0.25', '0.5', '1'],
    stock: 50,
    is_active: true,
    is_featured: false,
    badge: 'Crisp & Zesty',
    thumbnail_url: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'prod-6',
    category_id: 'cat-2',
    name: 'Tender Spinach (Palak)',
    name_urdu: 'تازہ پالک',
    slug: 'tender-spinach-palak',
    description: 'Crisp green organic spinach leaves, washed and bundled fresh every morning from Malir farms.',
    price: 60,
    unit: 'kg',
    weight_options: ['0.5', '1', '2'],
    stock: 80,
    is_active: true,
    is_featured: true,
    badge: 'Iron Rich',
    thumbnail_url: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'prod-7',
    category_id: 'cat-2',
    name: 'Fresh Green Okra (Bhindi)',
    name_urdu: 'بھنڈی',
    slug: 'fresh-green-okra-bhindi',
    description: 'Soft, tender ladyfingers without hard seeds. Cooks quickly into delicious bhindi masala.',
    price: 160,
    unit: 'kg',
    weight_options: ['0.5', '1', '2'],
    stock: 75,
    is_active: true,
    is_featured: true,
    badge: 'Tender Pick',
    thumbnail_url: 'https://images.unsplash.com/photo-1425543103986-22abb7d7e8d2?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'prod-8',
    category_id: 'cat-2',
    name: 'Sweet Green Peas (Matar)',
    name_urdu: 'مٹر',
    slug: 'sweet-green-peas-matar',
    description: 'Sweet, full pods filled with tender green peas. Perfect for pulao, keema, and aloo matar.',
    price: 180,
    unit: 'kg',
    weight_options: ['0.5', '1', '2'],
    stock: 70,
    is_active: true,
    is_featured: false,
    badge: 'Seasonal Sweet',
    thumbnail_url: 'https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'prod-9',
    category_id: 'cat-3',
    name: 'Farm Cucumbers (Kheera)',
    name_urdu: 'دیسی کھیرا',
    slug: 'farm-cucumbers-kheera',
    description: 'Crunchy, refreshing salad cucumbers picked at optimal maturity.',
    price: 90,
    unit: 'kg',
    weight_options: ['0.5', '1', '2'],
    stock: 110,
    is_active: true,
    is_featured: true,
    badge: 'Hydrating',
    thumbnail_url: 'https://images.unsplash.com/photo-1604977042946-1eecc30f269e?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'prod-10',
    category_id: 'cat-3',
    name: 'Aromatic Mint (Podina)',
    name_urdu: 'تازہ پودینہ',
    slug: 'aromatic-mint-podina',
    description: 'Fragrant garden mint bunches for chutney, raita, and refreshing summer drinks.',
    price: 30,
    unit: 'bunch',
    weight_options: ['1', '2', '5'],
    stock: 100,
    is_active: true,
    is_featured: false,
    badge: 'Garden Fresh',
    thumbnail_url: 'https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'prod-11',
    category_id: 'cat-3',
    name: 'Fresh Coriander (Hara Dhaniya)',
    name_urdu: 'ہرا دھنیا',
    slug: 'fresh-coriander-dhaniya',
    description: 'Vibrant green cilantro leaves with deep aroma for everyday garnishing.',
    price: 40,
    unit: 'bunch',
    weight_options: ['1', '2', '5'],
    stock: 100,
    is_active: true,
    is_featured: false,
    badge: 'Essential Garnish',
    thumbnail_url: 'https://images.unsplash.com/photo-1589135233689-d56214555815?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'prod-12',
    category_id: 'cat-3',
    name: 'Spicy Green Chillies (Hari Mirch)',
    name_urdu: 'ہری مرچ',
    slug: 'spicy-green-chillies-hari-mirch',
    description: 'Crisp green chillies with the right kick of heat.',
    price: 150,
    unit: 'kg',
    weight_options: ['0.25', '0.5', '1'],
    stock: 80,
    is_active: true,
    is_featured: false,
    badge: 'Hot & Zesty',
    thumbnail_url: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'prod-13',
    category_id: 'cat-4',
    name: 'Fresh Cauliflower (Phool Gobi)',
    name_urdu: 'پھول گوبھی',
    slug: 'fresh-cauliflower-phool-gobi',
    description: 'Dense, clean white cauliflower heads with crisp green protection leaves.',
    price: 110,
    unit: 'kg',
    weight_options: ['1', '2', '3'],
    stock: 70,
    is_active: true,
    is_featured: false,
    badge: 'Snow White',
    thumbnail_url: 'https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'prod-14',
    category_id: 'cat-4',
    name: 'Glossy Eggplant (Baingan)',
    name_urdu: 'بینگن',
    slug: 'glossy-eggplant-baingan',
    description: 'Smooth, shiny dark purple brinjals great for baingan bharta and pakoras.',
    price: 100,
    unit: 'kg',
    weight_options: ['0.5', '1', '2'],
    stock: 85,
    is_active: true,
    is_featured: false,
    badge: 'Tender Flesh',
    thumbnail_url: 'https://images.unsplash.com/photo-1615484477778-ca3b783256fd?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 'prod-15',
    category_id: 'cat-5',
    name: 'Weekly Kitchen Vegetable Box (10 KG)',
    name_urdu: 'ہفتہ وار فیملی سبزی کریٹ',
    slug: 'weekly-kitchen-vegetable-box',
    description: 'Complete weekly family vegetable pack: 3kg Aloo, 2kg Piyaz, 2kg Tamatar, 1kg Palak, 1kg Kheera, plus free Dhaniya, Podina & Hari Mirch pack!',
    price: 1250,
    unit: 'crate',
    weight_options: ['1', '2'],
    stock: 40,
    is_active: true,
    is_featured: true,
    badge: 'Save 15% • Best Value',
    thumbnail_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80'
  }
];

export const INITIAL_SETTINGS: ShopSettings = {
  id: 'main_settings',
  shop_name: 'I.A Vegetables Supplier',
  shop_subtitle: 'Fresh Farm Produce • Since 1990',
  ntn_number: '4260196-7',
  phone_number: '+92 341 3989260',
  whatsapp_number: '+92 341 3989260',
  shop_address: 'I.A vegetables shop, SITE Town, Keamari District, Karachi 75020',
  google_maps_url: 'https://www.google.com/maps/place/I.A+vegetables+shop/@24.8882505,66.9850563,21z/data=!4m6!3m5!1s0x3eb3150079cc1185:0x28632361d3a85fb9!8m2!3d24.8882505!4d66.9850563!16s%2Fg%2F11yx7kv0rs',
  plus_code: '7JP8VXQP+82',
  latitude: 24.8882505,
  longitude: 66.9850563,
  delivery_fee: 150,
  free_delivery_threshold: 1500,
  delivery_zones: [
    'SITE Town',
    'Clifton / DHA',
    'Gulshan-e-Iqbal',
    'North Nazimabad',
    'Saddar',
    'Malir',
    'Korangi',
    'PECHS',
    'Bahria Town Karachi',
    'Gulistan-e-Johar',
    'Orangi Town',
    'Keamari Area'
  ],
  payment_methods: {
    cod_enabled: true,
    jazzcash_enabled: true,
    jazzcash_title: 'I.A Vegetables',
    jazzcash_number: '0341-3989260',
    easypaisa_enabled: true,
    easypaisa_title: 'I.A Vegetables',
    easypaisa_number: '0341-3989260',
    bank_enabled: true,
    bank_name: 'Meezan Bank',
    bank_title: 'I.A Vegetables Supplier',
    bank_account: '0101-0102030405'
  },
  admin_pin: 'admi@iavegetables123@#'
};

export const INITIAL_HERO: HeroBanner = {
  id: 'main_hero',
  headline: 'Fresh Farm Vegetables Delivered Across Karachi',
  subheadline: 'Direct from the mandi to your kitchen. Hand-picked, sorted, and delivered fresh daily.',
  ticker_announcement: '🚚 Free delivery across Karachi on all orders above Rs. 1,500! Fresh morning harvest arrived.',
  badge_text: '100% Fresh Daily Harvest • Serving Since 1990'
};

export const INITIAL_COUPONS: Coupon[] = [
  { id: 'c-1', code: 'FREESHIP', discount_type: 'fixed', discount_value: 150, min_spend: 1000, is_active: true },
  { id: 'c-2', code: 'SUBZI100', discount_type: 'fixed', discount_value: 100, min_spend: 1200, is_active: true },
  { id: 'c-3', code: 'RAMADAN10', discount_type: 'percentage', discount_value: 10, min_spend: 1500, is_active: true }
];
